name: Generate Social Post Drafts

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  generate_social_posts:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get release version
        id: version
        shell: pwsh
        run: |
          $version = "${{ github.ref }}".Replace("refs/tags/", "")
          echo "version=$version" >> $env:GITHUB_OUTPUT

      - name: Generate fun dev post
        id: devpost
        shell: pwsh
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          $version = "${{ steps.version.outputs.version }}"
          $prompt = "Write a short and fun social media post about the new release of gq-to-sql-client version $version. Highlight cool new features for devs, use playful language, and include a project link and relevant hashtags like #TypeScript or #devtools."

          $outDir = "social-drafts/v$version"
          New-Item -ItemType Directory -Force -Path $outDir | Out-Null
          $outputFile = "$outDir/dev-post.md"
          "## gq-to-sql-client $version (Dev Post)" | Out-File -FilePath $outputFile -Encoding utf8

          $json = @{
            model = "gpt-3.5-turbo"
            messages = @(@{ role = "user"; content = $prompt })
            temperature = 0.7
          } | ConvertTo-Json -Depth 3

          $headers = @{
            "Content-Type"  = "application/json"
            "Authorization" = "Bearer $env:OPENAI_API_KEY"
          }

          $response = Invoke-RestMethod -Uri "https://api.openai.com/v1/chat/completions" -Method Post -Headers $headers -Body $json
          $response.choices[0].message.content | Out-File -Append -Encoding utf8 $outputFile

      - name: Generate LinkedIn post
        id: linkedinpost
        shell: pwsh
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          $version = "${{ steps.version.outputs.version }}"
          $prompt = "Write a professional, concise LinkedIn-style post for the release of gq-to-sql-client version $version. Summarize the technical improvements and include a clear call to action with a link to the GitHub release and to https://masem.at and also with hashtags."

          $outDir = "social-drafts/v$version"
          $outputFile = "$outDir/linkedin-post.md"
          "## gq-to-sql-client $version (LinkedIn Post)" | Out-File -FilePath $outputFile -Encoding utf8

          $json = @{
            model = "gpt-3.5-turbo"
            messages = @(@{ role = "user"; content = $prompt })
            temperature = 0.5
          } | ConvertTo-Json -Depth 3

          $headers = @{
            "Content-Type"  = "application/json"
            "Authorization" = "Bearer $env:OPENAI_API_KEY"
          }

          $response = Invoke-RestMethod -Uri "https://api.openai.com/v1/chat/completions" -Method Post -Headers $headers -Body $json
          $response.choices[0].message.content | Out-File -Append -Encoding utf8 $outputFile

      - name: Commit social post drafts
        shell: pwsh
        run: |
          git config --global user.name "masem-bot"
          git config --global user.email "actions@github.com"
          git add social-drafts/
          git commit -m "🤖 Social post drafts for v${{ steps.version.outputs.version }}"
          git push
