# .github/workflows/test.yml
name: Run Tests

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    test:
        runs-on: self-hosted

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Setup node
              uses: actions/setup-node@v3
              with: 
                node-version: 20
                cache: 'npm'
            
            - name: Run tests and save results
              id: tests
              run: |
                set -o pipefail
                npm run test 2>&1 | tee result.log

            - name: Upload tests result as PR comment
              if: github.event_name == 'pull_request'
              uses: actions/github-script@v7
              with:
                script: |
                    const fs = require('fs')
                    const output = fs.readFileSync('result.log', 'utf-8');
                    const truncated = output.length > 65000 ? output.slice(65000) : output;
                    const body = `### 🧪 Vitest Results\n\`\`\`\n${truncated}\n\`\`\``;
                    github.res.issues.createComment({
                        issue_number: context.issue_number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body
                    });
