# .github/workflows/use-shared-readme-builder.yml
name: Use Shared README Builder

on: 
  workflow_dispatch:

jobs:
  call-shared-workflow:
    uses: masem-at/masem-github-workflows/generate-readme.yml@main
